---
title: "App Name"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)

# core
library(tidyverse)
library(tidyquant)

# interactive visualizations
library(plotly)

# interact with databases
library(odbc)
library(RSQLite)
```

```{r}
# con <- dbConnect(RSQLite::SQLite(), "../00_data/bikes_database.db")

con <- dbConnect(RSQLite::SQLite(), "C:/Users/decicco1/OneDrive - Michigan State University/CSTATRedirects/Documents/R Studio Projects/Business-Science/DS4B 102-R Shiny Dashboards/DS4B_102_R_Shiny_Apps_1/00_data/bikes_database.db")

# dbListTables(con)
bikes_tbl <- tbl(con, "bikes")
bikeshops_tbl <- tbl(con, "bikeshops")
orderlines_tbl <- tbl(con, "orderlines")

processed_data_tbl <- orderlines_tbl %>% 
    left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id")) %>% 
    left_join(bikes_tbl, by = c("product.id"="bike.id")) %>%
    mutate(extended_price = quantity*price) %>%
    collect()

processed_data_tbl <- processed_data_tbl %>% 
    mutate(order.date=ymd(order.date)) %>% 
    separate(location, into=c("city","state"), sep=", ") %>% 
    select(order.date, order.id, order.line, state, quantity,
           price, extended_price)

dbDisconnect(con)

```

