---
title: "Sales Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(shinyjs)

# Core
library(tidyverse)
library(tidyquant)

# Interactive Visualizations
library(plotly)

# Modeling
library(parsnip)
library(xgboost)
library(timetk)

# Database
library(odbc)
library(RSQLite)


source("04_demand_forecast.r")
```

```{css}
.bootstrap-switch .bootstrap-switch-handle-on,
.bootstrap-switch .bootstrap-switch-handle-off,
.bootstrap-switch .bootstrap-switch-label {
    display: inline-block;
    vertical-align: baseline;
}
``` 



```{r dose-response-workshop-import-csv, eval=TRUE}

# if running as an .R file:
# Data <- read.csv("Dose_Response_App/data.csv", header = TRUE)

# When running as shiny:
Data <- read.csv("data.csv", header = TRUE)

# class(Data)
# names(Data)
# sapply(Data, class) 

```

```{r import-Model_List.csv}

# if running as an .R file:
# Model_List <- read.csv("Dose_Response_App/Model_List.csv.csv", header = TRUE)

# import the list of model names and commands:
Model_List <- read.csv("Model_List.csv", header = TRUE)


```

```{R dose-response-workshop-run-ANOVA-get-p-values}

# Run ANOVA and Extract P-values

Data$Drug = as.character(Data$Drug)
Data$Drug = tolower(Data$Drug)
DRUG.NAME = data.frame(unique(Data$Drug))
Drugs_cov = DRUG.NAME
names(Drugs_cov) = c("DRUG.NAME")
Drugs_cov$DRUG.NAME = as.character(Drugs_cov$DRUG.NAME)

for (name in Drugs_cov$DRUG.NAME){
     data = subset(Data, Drug == name)
#	   print(summary(aov(lm(Data$Response ~ Data$CONCEN.uM))))
	   Drugs_cov$pvalue[Drugs_cov$DRUG.NAME == name] = 
	       unlist(summary(aov(lm(Data$Response ~ Data$CONCEN.uM))))[9]} 

for (name in Drugs_cov$DRUG.NAME){
      Drugs_cov$pvaluecut[Drugs_cov$DRUG.NAME == name] = 
          ifelse(Drugs_cov$pvalue[Drugs_cov$DRUG.NAME == name] <= 0.01, "p <= 0.01", "p > 0.01")}

```


Column {.sidebar}
---------------------------------------------------------------

```{r}
useShinyjs(rmd = TRUE)


shinyWidgets::pickerInput(
  inputId  = "picker_drug_name", 
  label    = h4("Drug Name"), 
  choices  = unique(Drugs_cov$DRUG.NAME) %>% sort(), 
  selected = unique(Drugs_cov$DRUG.NAME) %>% sort() %>% first(), 
  multiple = FALSE,
  options  = list(
    `actions-box` = TRUE,
    size = 10,
    `selected-text-format` = "count > 3"
  )
)



shinyWidgets::pickerInput(
  inputId  = "picker_model_name", 
  label    = h4("Model to Use"), 
  choices  = unique(Model_List$Model_Name) %>% sort(), 
  selected = unique(Model_List$Model_Name) %>% sort() %>% first(), 
  multiple = FALSE,
  options  = list(
    `actions-box` = TRUE,
    size = 10,
    `selected-text-format` = "count > 3"
  )
)

# APPLY BUTTONS ------

br()
hr()
br()

actionButton(inputId = "apply", label = "Apply", icon = icon("play"))

actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))



observeEvent(eventExpr = input$reset, handlerExpr = {
  
 
  updatePickerInput(
  session = session, 
  inputId = "picker_drug_name", 
  selected = unique(Drugs_cov$DRUG.NAME) %>% sort() %>% first()
    )

  updatePickerInput(
  session = session, 
  inputId = "picker_model_name", 
  selected = unique(Model_List$Model_Name) %>% sort() %>% first()
    )
     
  shinyjs::delay(ms = 300, expr = {
    shinyjs::click(id = "apply")
  })
 
  
})
```



```{r dose-response-workshop-filter-data, eval=TRUE}

dataagg <- eventReactive(
  eventExpr = input$apply, 
                                             
  valueExpr = {

    data <- Data %>% filter(Drug %in% input$picker_drug_name)  
        
    # data <- Data %>% filter(Drug %in% input$picker_drug_name) %>% 
    #     dplyr::group_by(CONCEN.uM) %>% 
    #     dplyr::summarise(MEAN = mean(Response,na.rm = T),
    #                      SD = SD(Response,na.rm = T)
    #                      )
      
      # dataagg_temp = cbind(aggregate(data$Response, 
      #               by = list(data$CONCEN.uM), FUN = mean, na.rm = T), 
      #               aggregate(data$Response, 
      #               by = list(data$CONCEN.uM), FUN = sd, na.rm = T)$x)
      # 
      # names(dataagg_temp) = c("CONCEN.uM", "MEAN", "SD")
  },
  ignoreNULL = FALSE
)

# View(dataagg)




```


```{r create-model-row-reactive-object, eval=TRUE}

model_row_reactive <- reactive({
  
    Model_List %>%  dplyr::filter(Model_Name %in% input$picker_model_name) %>% 
        summarise(Model_Name = unique(Model_Name),
                  Model_Command = unique(fct_command))
    
})

 renderPrint(model_row_reactive())

```


```{r dose-response-workshop-model-command, eval=FALSE}

# fct_command <- eventReactive({
#       
#     Model_List %>%  dplyr::filter(Model_Name %in% input$picker_model_name) %>% 
#         summarise(Model_Command = unique(fct_command))
# 
#   },
#   ignoreNULL = FALSE
# )


     
renderPrint(model_row_reactive()$Model_Command)





```




Row {data-height=150}
---------------------------------------------------------------

```{r create-original-metrics, eval=FALSE}
summary_values_tbl <- reactive({
  
  processed_data_filtered_tbl() %>%
  
    summarize(
      health_metric = unique(order.id) %>% length(),
      wealth_metric = sum(extended_price),
      wise_metric   = (sum(str_detect(category_1, "Mountain")) / (sum(str_detect(category_1, "Road")) + 0.0001)) %>% 
        round(1)
    ) 
    # %>%
    # mutate(
    #   health_metric = health_metric %>% scales::number(big.mark = ","),
    #   wealth_metric = wealth_metric %>% scales::dollar(scale = 1e-6, accuracy = 0.1, suffix = "M")
    # )
  
})

# renderPrint(summary_values_tbl())

```


### Health

```{r, eval=FALSE}
renderValueBox({
  
  valueBox(
    value   = summary_values_tbl()$health_metric %>% scales::comma(), 
    caption = "Orders", 
    icon    = "fa-heartbeat", 
    color   = case_when(summary_values_tbl()$health_metric < 200 ~ "danger",
                        summary_values_tbl()$health_metric < 500 ~ "warning",
                        TRUE ~ "success"))
  
})


```


### Model Name

```{r, eval=FALSE}
renderValueBox({
  
  valueBox(
    value   =  model_row_reactive()$Model_Name, 
    caption = "Model Name", 
    icon    = "fa-money-check-alt")
  
})
```


### Wise

```{r, eval=FALSE}
renderValueBox({
  
  valueBox(
    value   = summary_values_tbl()$wise_metric, 
    caption = "Ratio, Mountain to Road", 
    icon    = "fa-brain", 
    color   = case_when(summary_values_tbl()$wise_metric < 0.5  ~ "warning",
                        summary_values_tbl()$wise_metric < 2.0   ~ "success",
                        TRUE ~ "warning"))
  
})
```


Row {data-height=850}
---------------------------------------------------------------

### Error Bar Plot

```{r, eval=FALSE}

geo_plot_tbl <- reactive({

  processed_data_filtered_tbl() %>%

    group_by(state) %>%
    summarise(total_revenue = sum(extended_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("State: {state}
                                 Revenue: {scales::dollar(total_revenue)}"))

})


# geo_plot_tbl <- processed_data_tbl %>%
#     group_by(state) %>%
#     summarise(total_revenue = sum(extended_price)) %>%
#     ungroup() %>%
#     mutate(label_text = str_glue("State: {state}
#                                  Revenue: {scales::dollar(total_revenue)}"))
```


```{r dose-response-workshop-print-filtered-aggregated-data, eval=FALSE}

dataagg_tbl <- reactive({
  
    
    print(data)
   # data %>% dplyr::group_by(CONCEN.uM) %>% 
   #       dplyr::summarise(MEAN = mean(Response,na.rm = T),
   #                        SD = SD(Response,na.rm = T)
   #                        )

    
})

renderPrint(dataagg_tbl())


```


```{r dose-response-workshop-print-filtered-aggregated-data-II, eval=TRUE}

dataagg_tbl <- reactive({
  
    
   
   data <- Data %>% dplyr::filter(Drug == input$picker_drug_name) %>% 
        dplyr::group_by(CONCEN.uM) %>%                             
           dplyr::summarise(MEAN = mean(Response,na.rm = T),
                            SD = sd(Response,na.rm = T)
                            )
   print(data)
  
   
})

# renderPrint(dataagg_tbl())


```



```{r dose-response-workshop-error-bar-plot, eval=TRUE}
output$plotly_1 <- renderPlotly(expr = {
 
errorbar_title = paste0("Plot with Error Bars:  Drug = ",input$picker_drug_name)
    
    dataagg_tbl() %>% ggplot(., aes(x = round(CONCEN.uM,2), y = MEAN)) + 
        scale_x_continuous(name = "CONCEN.uM", trans='log') +
        geom_errorbar(aes(ymin = MEAN - SD, ymax = MEAN + SD), width = .1, color = "green") +
        geom_line(color = "green") + geom_point(color = "green") + 
        theme_bw() + 
        theme_classic() +
        labs(title=errorbar_title,
        x ="Concentration (uM, log scale)", y = "Mean Response")
    

  
})

plotlyOutput(outputId = "plotly_1")

```



### Scatterplot of Response vs Dose


```{r set-up-model-statement, eval=TRUE}


model_statement <- reactive({
  
    
   statement <- paste0("drm(Response ~ CONCEN.uM, data = na.omit(dataagg_tbl()),",
                       model_row_reactive()$Model_Command,
                       ")")

})

 renderPrint(class(model_statement()))

```


```{r run-models, eval = TRUE}

# Select Model:

# 3-parameter log-logistic model           fct = LL.3u(upper = 100))
# 4-parameter log-logistic model           fct = LL.4()
# 3-parameter asymptotic regression model  fct = AR.3()
# 3-parameter exponential model            fct = EXD.3()
# two 3 parameter Weibull models           fct = W1.3()
# two 3-parameter Weibull models           fct = W2.3()
# 4-parameter Weibull models               fct = W1.4()
# 4-parameter Weibull model                fct = W2.4()
# 3-parameter Gompertz model               fct = G.3()
# 4-parameter Gompertz model               fct = G.4()


model_run <- reactive({
  
    
   model_run <- model_statement()

})

# renderPrint(class(model_run()))


```


```{r run-prediction, eval = FALSE}


# Set up prediction data set:

Con  <-  data.frame(seq(min(data$CONCEN.uM), max(data$CONCEN.uM), 
                        length.out = 1000)) %>% 
    dplyr::rename(CONCEN.uM =                       seq.min.data.CONCEN.uM...max.data.CONCEN.uM...length.out...1000.)

# View(Con)

Fit = data.frame(predict(model_selected, newdata = Con))
Fit = data.frame(Con, Fit)
names(Fit) = c("CONCEN.uM", "Response")

```


```{r prepare-data-for-scatterplot-dose-response, eval=TRUE}

scatterplot_tbl <- reactive({

     data <- Data %>% dplyr::filter(Drug == input$picker_drug_name) 

     print(data)
})




# renderPrint(scatterplot_tbl())


  
```



```{r plot-scatterplot-dose-response-data, eval=TRUE}



output$plotly_2 <- renderPlotly({

scatterplot_title = paste0("Dose and Response:  Drug = ", input$picker_drug_name, "\n Model = ",
                           model_row_reactive()$Model_Name,
                           "\n Model Command = ",model_row_reactive()$Model_Command, 
                           "\n Model Statement =",model_statement)
    
    scatterplot_tbl() %>% ggplot(., aes(x = round(CONCEN.uM,2), y = Response)) + 
        scale_x_continuous(name = "CONCEN.uM", trans='log') +
        geom_point() +
        theme_bw() + 
        theme_classic() +
        labs(title=scatterplot_title,
        x ="Concentration (uM, log scale)", y = "Response") +
        theme(plot.title = element_text(size = 10, vjust = 10, face="bold")) +
        theme(plot.margin = unit(c(1,1,1,1), "cm"))


})

plotlyOutput(outputId = "plotly_2")
  
```